### ISSUE TITLE
第一次需求大会以及定下技术栈

### ISSUE THREAD

**Issue by SaberDa** [XDUPSMC3Team/ProjectDoc#2]
时间暂定下周二晚7点？或者早些也行
地点G302
带电脑带纸笔

Ps：若时间有问题的话，在issue下留言即可

**Comment by SaberDa** [comment]
新的问题，时间是下课后，还是下午，或者是晚上

**Comment by ACERY1** [comment]
ok

**Comment by SaberDa** [comment]
> ok

这个ok是指哪个时间段？

**Comment by ACERY1** [comment]
> > ok
> 
> 这个ok是指哪个时间段？

今天晚上7点吧
